In [ ]:
!pip install nltk

In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
from collections import Counter #Counts frequency of elements in a list or text.
from torch.utils.data import Dataset, DataLoader
from nltk.tokenize import word_tokenize  #Splits text into individual words/tokens.
import nltk # Used for NLP tasks like tokenization, stemming, stopword removal, etc

In [ ]:
document = """The Last Train Journey

On a cold winter evening, Daniel arrived at the old railway station carrying a small leather bag.
The station was nearly empty except for a few passengers waiting quietly on wooden benches.
A loud whistle echoed through the air as the final train of the night slowly entered the platform.

Daniel checked the ticket in his pocket and walked toward the train.
The metal doors opened with a creaking sound and warm air rushed outside.
Inside the train, yellow lights flickered softly above rows of empty seats.

He chose a seat beside the window and placed his bag carefully near his feet.
As the train began to move, the city lights slowly disappeared behind thick clouds of fog.
Snow started falling gently outside while distant mountains appeared under the moonlight.

Across the aisle sat an elderly woman reading an old book with a blue cover.
Every few minutes she looked outside the window as if searching for something familiar.
Daniel noticed a silver necklace around her neck shaped like a small compass.

After several hours, the train stopped at a remote station surrounded by tall pine trees.
Very few people entered or left the train at that place.
A strange silence covered the station as the doors closed once again.

Curious about the woman, Daniel finally started a conversation.
The woman introduced herself as Eleanor and explained that she was returning to her hometown after many years.
She said the town was hidden deep within the northern mountains and was known for its beautiful frozen lake.

As the journey continued, Eleanor shared stories from her childhood.
She described colorful festivals, music performances, and lanterns floating across the lake during winter nights.
Daniel listened carefully while the train moved through snowy valleys and dark forests.

Near midnight, the train suddenly slowed down because heavy snow had covered the tracks ahead.
Passengers became nervous and began discussing possible delays.
Conductors moved through the cabins trying to calm everyone.

Daniel looked outside and saw workers removing snow under bright floodlights.
The freezing wind shook the train slightly while snow continued falling from the dark sky.
Despite the delay, Eleanor remained calm and continued telling her stories.

Several hours later, the tracks were finally cleared and the train resumed its journey.
The passengers sighed with relief as warm coffee was served throughout the cabins.
Daniel and Eleanor continued talking about travel, history, and forgotten places around the world.

Just before sunrise, the train reached the mountain town.
The station was small but beautifully decorated with glowing lamps and snow-covered rooftops.
People wearing thick winter coats walked slowly across the icy streets.

Before leaving, Eleanor handed Daniel a folded piece of paper.
Inside it was a drawing of the frozen lake along with a short message thanking him for the conversation.
Daniel smiled and carefully placed the paper inside his notebook.

As the train departed once again, Daniel stood on the platform watching the sunrise over the mountains.
The cold air, quiet streets, and distant church bells created a peaceful atmosphere he would never forget.
Years later, Daniel would still remember that mysterious winter journey and the stories shared by Eleanor on the last train of the night.
"""

In [ ]:
# NLTK does NOT come with pretrained tokenizers by default.

# Tokenization
nltk.download('punkt')

# Some newer NLTK versions require additional tokenizer tables.
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


True

# Tokenize

In [ ]:
tokens = word_tokenize(document.lower())
tokens

['the',
 'last',
 'train',
 'journey',
 'on',
 'a',
 'cold',
 'winter',
 'evening',
 ',',
 'daniel',
 'arrived',
 'at',
 'the',
 'old',
 'railway',
 'station',
 'carrying',
 'a',
 'small',
 'leather',
 'bag',
 '.',
 'the',
 'station',
 'was',
 'nearly',
 'empty',
 'except',
 'for',
 'a',
 'few',
 'passengers',
 'waiting',
 'quietly',
 'on',
 'wooden',
 'benches',
 '.',
 'a',
 'loud',
 'whistle',
 'echoed',
 'through',
 'the',
 'air',
 'as',
 'the',
 'final',
 'train',
 'of',
 'the',
 'night',
 'slowly',
 'entered',
 'the',
 'platform',
 '.',
 'daniel',
 'checked',
 'the',
 'ticket',
 'in',
 'his',
 'pocket',
 'and',
 'walked',
 'toward',
 'the',
 'train',
 '.',
 'the',
 'metal',
 'doors',
 'opened',
 'with',
 'a',
 'creaking',
 'sound',
 'and',
 'warm',
 'air',
 'rushed',
 'outside',
 '.',
 'inside',
 'the',
 'train',
 ',',
 'yellow',
 'lights',
 'flickered',
 'softly',
 'above',
 'rows',
 'of',
 'empty',
 'seats',
 '.',
 'he',
 'chose',
 'a',
 'seat',
 'beside',
 'the',
 'window',
 'a

# Build vocabs

In [ ]:
#build vocab
vocab = { '<unk>' : 0 }

In [ ]:
for token in Counter(tokens).keys():
  if token not in vocab:
    vocab[token]= len(vocab)

vocab

{'<unk>': 0,
 'the': 1,
 'last': 2,
 'train': 3,
 'journey': 4,
 'on': 5,
 'a': 6,
 'cold': 7,
 'winter': 8,
 'evening': 9,
 ',': 10,
 'daniel': 11,
 'arrived': 12,
 'at': 13,
 'old': 14,
 'railway': 15,
 'station': 16,
 'carrying': 17,
 'small': 18,
 'leather': 19,
 'bag': 20,
 '.': 21,
 'was': 22,
 'nearly': 23,
 'empty': 24,
 'except': 25,
 'for': 26,
 'few': 27,
 'passengers': 28,
 'waiting': 29,
 'quietly': 30,
 'wooden': 31,
 'benches': 32,
 'loud': 33,
 'whistle': 34,
 'echoed': 35,
 'through': 36,
 'air': 37,
 'as': 38,
 'final': 39,
 'of': 40,
 'night': 41,
 'slowly': 42,
 'entered': 43,
 'platform': 44,
 'checked': 45,
 'ticket': 46,
 'in': 47,
 'his': 48,
 'pocket': 49,
 'and': 50,
 'walked': 51,
 'toward': 52,
 'metal': 53,
 'doors': 54,
 'opened': 55,
 'with': 56,
 'creaking': 57,
 'sound': 58,
 'warm': 59,
 'rushed': 60,
 'outside': 61,
 'inside': 62,
 'yellow': 63,
 'lights': 64,
 'flickered': 65,
 'softly': 66,
 'above': 67,
 'rows': 68,
 'seats': 69,
 'he': 70,
 'chose

In [ ]:
len(vocab)

284

# Extract sentence from data

In [ ]:
input_sentences = document.split('\n')

In [ ]:
input_sentences[3]

'The station was nearly empty except for a few passengers waiting quietly on wooden benches.'

In [ ]:
def text_to_indices(sentence,vocab):
  numerical_sentence = []
  for token in sentence:
    if token in vocab:
      numerical_sentence.append(vocab[token])
    else:
      numerical_sentence.append(vocab['<unk>'])

  return numerical_sentence

In [ ]:
input_numerical_sentence= []
for sentence in input_sentences:
  input_numerical_sentence.append(text_to_indices(word_tokenize(sentence.lower()),vocab))


In [ ]:
input_numerical_sentence

[[1, 2, 3, 4],
 [],
 [5, 6, 7, 8, 9, 10, 11, 12, 13, 1, 14, 15, 16, 17, 6, 18, 19, 20, 21],
 [1, 16, 22, 23, 24, 25, 26, 6, 27, 28, 29, 30, 5, 31, 32, 21],
 [6, 33, 34, 35, 36, 1, 37, 38, 1, 39, 3, 40, 1, 41, 42, 43, 1, 44, 21],
 [],
 [11, 45, 1, 46, 47, 48, 49, 50, 51, 52, 1, 3, 21],
 [1, 53, 54, 55, 56, 6, 57, 58, 50, 59, 37, 60, 61, 21],
 [62, 1, 3, 10, 63, 64, 65, 66, 67, 68, 40, 24, 69, 21],
 [],
 [70, 71, 6, 72, 73, 1, 74, 50, 75, 48, 20, 76, 77, 48, 78, 21],
 [38, 1, 3, 79, 80, 81, 10, 1, 82, 64, 42, 83, 84, 85, 86, 40, 87, 21],
 [88, 89, 90, 91, 61, 92, 93, 94, 95, 96, 1, 97, 21],
 [],
 [98, 1, 99, 100, 101, 102, 103, 104, 101, 14, 105, 56, 6, 106, 107, 21],
 [108, 27, 109, 110, 111, 61, 1, 74, 38, 112, 113, 26, 114, 115, 21],
 [11, 116, 6, 117, 118, 119, 120, 121, 122, 123, 6, 18, 124, 21],
 [],
 [125, 126, 127, 10, 1, 3, 128, 13, 6, 129, 16, 130, 131, 132, 133, 134, 21],
 [135, 27, 136, 43, 137, 138, 1, 3, 13, 139, 140, 21],
 [6, 141, 142, 143, 1, 16, 38, 1, 54, 144, 145, 146

# training Sequence form

In [ ]:
training_sequence = []
for sentence in input_numerical_sentence:
  for i in range(1,len(sentence)):
    training_sequence.append(sentence[:i+1])

In [ ]:
training_sequence

[[1, 2],
 [1, 2, 3],
 [1, 2, 3, 4],
 [5, 6],
 [5, 6, 7],
 [5, 6, 7, 8],
 [5, 6, 7, 8, 9],
 [5, 6, 7, 8, 9, 10],
 [5, 6, 7, 8, 9, 10, 11],
 [5, 6, 7, 8, 9, 10, 11, 12],
 [5, 6, 7, 8, 9, 10, 11, 12, 13],
 [5, 6, 7, 8, 9, 10, 11, 12, 13, 1],
 [5, 6, 7, 8, 9, 10, 11, 12, 13, 1, 14],
 [5, 6, 7, 8, 9, 10, 11, 12, 13, 1, 14, 15],
 [5, 6, 7, 8, 9, 10, 11, 12, 13, 1, 14, 15, 16],
 [5, 6, 7, 8, 9, 10, 11, 12, 13, 1, 14, 15, 16, 17],
 [5, 6, 7, 8, 9, 10, 11, 12, 13, 1, 14, 15, 16, 17, 6],
 [5, 6, 7, 8, 9, 10, 11, 12, 13, 1, 14, 15, 16, 17, 6, 18],
 [5, 6, 7, 8, 9, 10, 11, 12, 13, 1, 14, 15, 16, 17, 6, 18, 19],
 [5, 6, 7, 8, 9, 10, 11, 12, 13, 1, 14, 15, 16, 17, 6, 18, 19, 20],
 [5, 6, 7, 8, 9, 10, 11, 12, 13, 1, 14, 15, 16, 17, 6, 18, 19, 20, 21],
 [1, 16],
 [1, 16, 22],
 [1, 16, 22, 23],
 [1, 16, 22, 23, 24],
 [1, 16, 22, 23, 24, 25],
 [1, 16, 22, 23, 24, 25, 26],
 [1, 16, 22, 23, 24, 25, 26, 6],
 [1, 16, 22, 23, 24, 25, 26, 6, 27],
 [1, 16, 22, 23, 24, 25, 26, 6, 27, 28],
 [1, 16, 22, 23, 24, 2

In [ ]:
len(training_sequence)

555

In [ ]:
training_sequence[:5]

[[1, 2], [1, 2, 3], [1, 2, 3, 4], [5, 6], [5, 6, 7]]

In [ ]:
len_list = []
for sequence in training_sequence:
  len_list.append(len(sequence))

In [ ]:
max(len_list)

25

# Padding

In [ ]:
#logic
[0]* (max(len_list)-len(sequence))

[]

In [ ]:
padded_training_sequence = []
for sequence in training_sequence:
  padded_training_sequence.append( [0]* (max(len_list)-len(sequence)) + sequence  )


In [ ]:
len(padded_training_sequence[0])

25

In [ ]:
padded_training_sequence[0]

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2]

In [ ]:
padded_training_sequence[6]

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 6, 7, 8, 9]

# tensor convert


In [ ]:
padded_training_sequence = torch.tensor(padded_training_sequence,dtype=torch.long)

In [ ]:
padded_training_sequence

tensor([[  0,   0,   0,  ...,   0,   1,   2],
        [  0,   0,   0,  ...,   1,   2,   3],
        [  0,   0,   0,  ...,   2,   3,   4],
        ...,
        [  0,   0, 158,  ...,   3,  40,   1],
        [  0, 158, 223,  ...,  40,   1,  41],
        [158, 223,  10,  ...,   1,  41,  21]])

In [ ]:
X = padded_training_sequence[:, :-1]

In [ ]:
X

tensor([[  0,   0,   0,  ...,   0,   0,   1],
        [  0,   0,   0,  ...,   0,   1,   2],
        [  0,   0,   0,  ...,   1,   2,   3],
        ...,
        [  0,   0, 158,  ...,   2,   3,  40],
        [  0, 158, 223,  ...,   3,  40,   1],
        [158, 223,  10,  ...,  40,   1,  41]])

In [ ]:
y = padded_training_sequence[:,-1]

In [ ]:
y

tensor([  2,   3,   4,   6,   7,   8,   9,  10,  11,  12,  13,   1,  14,  15,
         16,  17,   6,  18,  19,  20,  21,  16,  22,  23,  24,  25,  26,   6,
         27,  28,  29,  30,   5,  31,  32,  21,  33,  34,  35,  36,   1,  37,
         38,   1,  39,   3,  40,   1,  41,  42,  43,   1,  44,  21,  45,   1,
         46,  47,  48,  49,  50,  51,  52,   1,   3,  21,  53,  54,  55,  56,
          6,  57,  58,  50,  59,  37,  60,  61,  21,   1,   3,  10,  63,  64,
         65,  66,  67,  68,  40,  24,  69,  21,  71,   6,  72,  73,   1,  74,
         50,  75,  48,  20,  76,  77,  48,  78,  21,   1,   3,  79,  80,  81,
         10,   1,  82,  64,  42,  83,  84,  85,  86,  40,  87,  21,  89,  90,
         91,  61,  92,  93,  94,  95,  96,   1,  97,  21,   1,  99, 100, 101,
        102, 103, 104, 101,  14, 105,  56,   6, 106, 107,  21,  27, 109, 110,
        111,  61,   1,  74,  38, 112, 113,  26, 114, 115,  21, 116,   6, 117,
        118, 119, 120, 121, 122, 123,   6,  18, 124,  21, 126, 1

In [ ]:
len(X)

555

In [ ]:
len(y)

555

# Custom Dataset and Dataloader

In [ ]:
class CustomDataset(Dataset):
  def __init__(self,X,y):
    self.X = X
    self.y = y

  def __len__(self):
    return self.X.shape[0]

  def __getitem__(self, idx) :
    return self.X[idx], self.y[idx]

In [ ]:
dataset = CustomDataset(X,y)

In [ ]:
len(dataset)

555

In [ ]:
dataloader = DataLoader(dataset,batch_size=32,shuffle=True)

In [ ]:
for input , output in dataloader:
  print(input,output)





tensor([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0, 125, 126, 127,  10],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 135,
          27, 136,  43, 137, 138,   1,   3,  13, 139, 140],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,  62, 259,  22,   6, 260],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0, 239],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  11,
          45,   1,  46,  47,  48,  49,  50,  51,  52,   1],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           1, 214, 215, 216,   1,   3, 217,  92,  88, 170],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         126, 127, 223,  10,   1, 197, 224, 149, 225,  50],
        [  0,   0,   0,   0

In [ ]:
X.shape

torch.Size([555, 24])

In [ ]:
y.shape

torch.Size([555])

In [ ]:
X[0]

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1])

In [ ]:
X[554]

tensor([158, 223,  10,  11, 278, 281, 282, 139, 283,   8,   4,  50,   1, 172,
        171, 131, 153,   5,   1,   2,   3,  40,   1,  41])

In [ ]:
# X[555]

In [ ]:
len(dataset)

555

In [ ]:
len(vocab)

284

In [ ]:
len(dataset[0])

2

In [ ]:
len(dataset[0][0])

24

In [ ]:
dataset[0]

(tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]),
 tensor(2))

# LSTM Cell

In [ ]:
class LSTMModel(nn.Module):
  def __init__(self,vocab_size):
    super().__init__()
    self.embedding = nn.Embedding(vocab_size,100)
    self.lstm = nn.LSTM(100,150,batch_first=True)
    self.fc = nn.Linear(150,vocab_size)

  def forward(self,x):
    embedded = self.embedding(x)
    intermediate_hidden_states,(final_hidden_state,final_cell_state) = self.lstm(embedded)
    output = self.fc(final_hidden_state.squeeze(0))
    return output




In [ ]:
model = LSTMModel(len(vocab))

In [ ]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [ ]:
model.to(device)

LSTMModel(
  (embedding): Embedding(284, 100)
  (lstm): LSTM(100, 150, batch_first=True)
  (fc): Linear(in_features=150, out_features=284, bias=True)
)

In [ ]:
len(vocab)

284

In [ ]:
x = nn.Embedding(284,100)
y = nn.LSTM(100,150,batch_first=True)
z = nn.Linear(150, 284)

In [ ]:
len(dataset)

555

In [ ]:
dataset[0][0]

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1])

In [ ]:
dataset[0][0].shape

torch.Size([24])

In [ ]:
dataset[0][0].unsqueeze(0).shape

torch.Size([1, 24])

In [ ]:
a = dataset[0][0].unsqueeze(0)
a

tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [ ]:
x(a)

tensor([[[ 0.7581, -0.3483,  0.7557,  ..., -0.1916,  0.8094,  1.8767],
         [ 0.7581, -0.3483,  0.7557,  ..., -0.1916,  0.8094,  1.8767],
         [ 0.7581, -0.3483,  0.7557,  ..., -0.1916,  0.8094,  1.8767],
         ...,
         [ 0.7581, -0.3483,  0.7557,  ..., -0.1916,  0.8094,  1.8767],
         [ 0.7581, -0.3483,  0.7557,  ..., -0.1916,  0.8094,  1.8767],
         [ 0.3892, -1.1616,  2.0321,  ..., -0.6617, -0.5098, -0.4598]]],
       grad_fn=<EmbeddingBackward0>)

In [ ]:
x(a).shape

torch.Size([1, 24, 100])

In [ ]:
b = x(a)

In [ ]:
y(b)

(tensor([[[-0.2606, -0.0238,  0.2158,  ..., -0.0460,  0.1583, -0.0300],
          [-0.3660, -0.0063,  0.2884,  ..., -0.0924,  0.2086, -0.0519],
          [-0.4099,  0.0094,  0.3136,  ..., -0.1289,  0.2236, -0.0664],
          ...,
          [-0.4408,  0.0338,  0.3215,  ..., -0.2106,  0.2229, -0.0928],
          [-0.4408,  0.0338,  0.3215,  ..., -0.2106,  0.2229, -0.0928],
          [-0.1613,  0.1651,  0.1796,  ..., -0.1906,  0.1478, -0.1495]]],
        grad_fn=<TransposeBackward0>),
 (tensor([[[-0.1613,  0.1651,  0.1796,  0.0030, -0.2293,  0.0398, -0.2199,
             0.0029,  0.0571,  0.0389,  0.2035, -0.2911,  0.0370, -0.1772,
             0.1876, -0.1191,  0.0021,  0.1272, -0.0766,  0.0557, -0.0281,
            -0.1187,  0.0936,  0.3465,  0.0955, -0.2410, -0.0209,  0.2085,
             0.0318, -0.0499, -0.2423,  0.0860,  0.0778, -0.0588, -0.2162,
            -0.0943,  0.1186, -0.0944, -0.1183, -0.1366, -0.1022, -0.0755,
             0.1418, -0.1317, -0.0695,  0.0083,  0.0966,  0.02

In [ ]:
len(y(b))

2

In [ ]:
c ,d = y(b)

In [ ]:
c.shape  #Set of all intermediate hidden state

torch.Size([1, 24, 150])

In [ ]:
len(y(b))

2

In [ ]:
len(d)

2

In [ ]:
e, f = d


In [ ]:
e.shape  #Cell state

torch.Size([1, 1, 150])

In [ ]:
f.shape

torch.Size([1, 1, 150])

In [ ]:
f_temp = f.squeeze(0).shape
f_temp

torch.Size([1, 150])

In [ ]:
f_temp = f.squeeze(0)

In [ ]:
z(f_temp)

tensor([[-2.0454e-01,  8.3461e-02, -1.8877e-01,  2.2007e-01,  1.8147e-01,
         -1.8800e-01,  8.1308e-03, -4.2594e-02, -1.3671e-02,  1.0905e-01,
          2.6091e-01, -1.8555e-01,  8.8454e-02,  4.5944e-02,  1.4708e-01,
         -3.4520e-02,  1.7865e-01,  2.8070e-01, -2.9270e-01,  4.2083e-02,
         -3.0802e-01, -1.5370e-02,  5.0330e-02,  4.4479e-02,  3.6018e-01,
         -3.5077e-01, -1.3169e-01, -1.1586e-01,  3.6021e-02, -1.0200e-01,
         -6.4890e-02,  6.5657e-02,  2.2333e-01, -6.1278e-02, -7.5175e-02,
         -1.6946e-01,  3.4851e-01,  6.2156e-02,  1.9777e-01, -2.6694e-02,
         -2.6443e-01,  1.1178e-01, -3.9136e-02, -2.1322e-01, -4.0179e-02,
          1.8449e-01,  3.1339e-01,  2.1164e-01, -1.4381e-01,  2.0725e-01,
         -2.1018e-01, -9.4450e-02, -1.0060e-01, -4.0577e-01,  1.7881e-01,
         -2.4588e-01,  1.3230e-01, -2.3034e-01,  2.8683e-01, -1.7178e-01,
         -6.5782e-02,  2.3429e-01,  3.2230e-01, -3.4912e-01,  2.0198e-01,
         -1.8478e-01, -5.9091e-02,  1.

In [ ]:
len(f_temp[0])

150

In [ ]:
len(z(f_temp)[0])

284

In [ ]:
len(vocab)

284

In [ ]:
for batch_x , batch_y in dataloader:
  print(batch_x, batch_y)

tensor([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   1,   7,  37,  10, 272, 253,  10],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0, 238, 239, 240,  10,   1,   3, 241,   1, 242],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   1,   2,   3],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0, 135,  27, 136,  43, 137, 138,   1],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0, 238],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   1],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0, 135,  27, 136,  43, 137, 138],
        [  0,   0,   0,   0

# Training loop

In [ ]:
epochs = 50
learning_rate = 0.001

criterion = nn.CrossEntropyLoss()

optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)


# training loop

for epoch in range(epochs):
  total_loss = 0

  for batch_x, batch_y in dataloader:

    batch_x, batch_y = batch_x.to(device), batch_y.to(device)

    optimizer.zero_grad()

    output = model(batch_x)

    loss = criterion(output, batch_y)

    loss.backward()

    optimizer.step()

    total_loss = total_loss + loss.item()

  print(f"Epoch: {epoch + 1}, Loss: {total_loss:.4f}")

Epoch: 1, Loss: 101.3150
Epoch: 2, Loss: 95.6407
Epoch: 3, Loss: 87.7959
Epoch: 4, Loss: 82.0953
Epoch: 5, Loss: 76.8633
Epoch: 6, Loss: 71.6796
Epoch: 7, Loss: 66.1665
Epoch: 8, Loss: 61.0531
Epoch: 9, Loss: 55.3373
Epoch: 10, Loss: 50.0085
Epoch: 11, Loss: 45.5809
Epoch: 12, Loss: 40.7089
Epoch: 13, Loss: 36.1776
Epoch: 14, Loss: 32.3358
Epoch: 15, Loss: 28.8712
Epoch: 16, Loss: 25.6386
Epoch: 17, Loss: 22.7243
Epoch: 18, Loss: 20.0638
Epoch: 19, Loss: 17.8294
Epoch: 20, Loss: 15.9089
Epoch: 21, Loss: 14.2351
Epoch: 22, Loss: 12.6944
Epoch: 23, Loss: 11.4866
Epoch: 24, Loss: 10.4084
Epoch: 25, Loss: 9.4385
Epoch: 26, Loss: 8.6477
Epoch: 27, Loss: 7.8401
Epoch: 28, Loss: 7.4624
Epoch: 29, Loss: 6.6515
Epoch: 30, Loss: 6.3489
Epoch: 31, Loss: 5.7037
Epoch: 32, Loss: 5.4356
Epoch: 33, Loss: 5.2105
Epoch: 34, Loss: 4.7431
Epoch: 35, Loss: 4.5377
Epoch: 36, Loss: 4.3494
Epoch: 37, Loss: 4.0651
Epoch: 38, Loss: 3.8780
Epoch: 39, Loss: 3.6918
Epoch: 40, Loss: 3.5904
Epoch: 41, Loss: 3.4626


# Prediction

In [ ]:
max(len_list)

25

In [ ]:
#logic
[0]* (25-len(numerical_text)) + numerical_text

In [ ]:
def prediction(model,vocab,text):

  #tokenize
  tokenized_text = word_tokenize(text.lower())

  # print(tokenized_text)


  #numerical indices
  numerical_text = text_to_indices(tokenized_text,vocab)

  # print(numerical_text)

  #padding
  padded_text = torch.tensor([0]* (25-len(numerical_text)) + numerical_text , dtype=torch.long).unsqueeze(0)

  # print(padded_text)

  # print(len(padded_text))

  # print(padded_text.shape)


  #send to model
  output = model(padded_text)

  # print("model's output",output)

  # print("printing total_elements",len(output[0]))

  #predicted index

  value, index = torch.max(output,dim=1)

  # print(f"printing value and index {value}, {index}")

  # print(f"printing  index  {index}")

  # print("printing the word ")

  # print(list(vocab.keys())[index])

  #merge with text

  return text + " " + list(vocab.keys())[index]





In [ ]:
prediction(model,vocab,"Hi how are you the station was")

'Hi how are you the station was nearly'

In [ ]:
len(vocab)

284

In [ ]:
document.split('\n')

['The Last Train Journey',
 '',
 'On a cold winter evening, Daniel arrived at the old railway station carrying a small leather bag.',
 'The station was nearly empty except for a few passengers waiting quietly on wooden benches.',
 'A loud whistle echoed through the air as the final train of the night slowly entered the platform.',
 '',
 'Daniel checked the ticket in his pocket and walked toward the train.',
 'The metal doors opened with a creaking sound and warm air rushed outside.',
 'Inside the train, yellow lights flickered softly above rows of empty seats.',
 '',
 'He chose a seat beside the window and placed his bag carefully near his feet.',
 'As the train began to move, the city lights slowly disappeared behind thick clouds of fog.',
 'Snow started falling gently outside while distant mountains appeared under the moonlight.',
 '',
 'Across the aisle sat an elderly woman reading an old book with a blue cover.',
 'Every few minutes she looked outside the window as if searching for

# Generate Automatically

In [ ]:
import time
num_tokens = 20
input_text= 'Daniel checked the ticket'

for i in range(num_tokens):
  output_text = prediction(model,vocab,input_text)
  print(output_text)
  input_text = output_text
  time.sleep(0.5)


Daniel checked the ticket in
Daniel checked the ticket in his
Daniel checked the ticket in his pocket
Daniel checked the ticket in his pocket and
Daniel checked the ticket in his pocket and walked
Daniel checked the ticket in his pocket and walked toward
Daniel checked the ticket in his pocket and walked toward the
Daniel checked the ticket in his pocket and walked toward the train
Daniel checked the ticket in his pocket and walked toward the train .
Daniel checked the ticket in his pocket and walked toward the train . .
Daniel checked the ticket in his pocket and walked toward the train . . .
Daniel checked the ticket in his pocket and walked toward the train . . . .
Daniel checked the ticket in his pocket and walked toward the train . . . . .
Daniel checked the ticket in his pocket and walked toward the train . . . . . .
Daniel checked the ticket in his pocket and walked toward the train . . . . . . .
Daniel checked the ticket in his pocket and walked toward the train . . . . . . . .

# Accuracy calculation

In [ ]:
def calculate_accuracy(model,dataloader,device):

  model.eval() #set the model to evaluation mode

  correct = 0
  total = 0

  with torch.no_grad():
    for batch_x, batch_y in dataloader:
      # print(len(batch_x)),len(batch_y)
      batch_x, batch_y = batch_x.to(device), batch_y.to(device)

      #get model prediction
      output = model(batch_x)

      # print(len(output[0]))

      #get the predictec word indices

      _, predicted = torch.max(output,dim=1)

      # print("printing predicted",predicted)

      #compare wityh actual label

      # print("printing y lable",batch_y)

      # print(predicted == batch_y)
      correct += (predicted == batch_y).sum().item()

      # print(correct)
      # print("working with total",batch_y.size())
      total += batch_y.size(0)

    accuracy = correct / total * 100
    return accuracy






In [ ]:
accuracy = calculate_accuracy(model,dataloader,device)

print(f" Model accuracy {accuracy :.2f}%")

 Model accuracy 96.94%
